### ISSUE TITLE
The text in the clock(time setup) popup is not easily visible due to colours & contrast.

### ISSUE THREAD

**Issue by shreyp135** [criticalAY/Neer#3]
###### Reproduction Steps

1. Set wake up/sleep time in initial setup or in settings after.

###### Expected Result
The text should be easily.

###### Actual Result
the text is not very easily visible because of the colours and contrast of dismiss/confirm and a.m/p.m selector.

![image](https://github.com/criticalAY/Neer/assets/152720574/a23ae724-4bff-4fe0-870c-dde7f104000f)

**Comment by criticalAY** [comment]
Fixed in the latest commit. sorry directly pushed it to the repo
