### ISSUE TITLE
Changing notification internal does nothing

### ISSUE THREAD

**Issue by MrChocolatine** [criticalAY/Neer#8]
###### Reproduction Steps

1. Open app
1. In the top left corner, tap the notification icon
1. Tap the `Notification interval` option
1. Enter a new value in the field `Interval in Hrs`
   a. For instance: `2.0` or even just `2`
1. Tap the `Confirm` button
1. The notification internal still shows the value `1.0 Hrs`

###### Expected Result

The notification internal should show the new value manually entered.

###### Actual Result

The notification internal keeps showing the default value of `1.0 Hrs`

###### Debug info

- OS: GrapheneOS
- Android: v14
- Phone: Pixel 6a

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release

**Comment by criticalAY** [comment]
Hey! thanks for reporting it, it will be fixed in next alpha

**Comment by MrChocolatine** [comment]
How often do you release stable version?
Can't you backport this tiny fix and then release a patch version?

**Comment by criticalAY** [comment]
Stable release a week or so just want to introduce the custom notification feature then we will go live
